CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(200) NOT NULL,
role VARCHAR(50) NOT NULL DEFAULT 'user',
refresh_token VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE positions (
    positions_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    positions_code VARCHAR(100) NOT NULL,
    positions_name VARCHAR(255) NOT NULL,
    id INT NOT NULL,    
    FOREIGN KEY (id) REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);